### ISSUE TITLE
`ModuleNotFoundError` when executing `gotm_build.py`

### ISSUE THREAD

**Issue by glwagner** [qingli411/gotmtool#1]
Hi @qingli411 !

I cloned the repo and tried to run

```python
$ python gotm_build.py
```

but received an error:

```python
(base) gregorywagner:gotmtool/ (master) $ python gotm_build.py                                                                                                                      [8:05:39]
Traceback (most recent call last):
  File "/Users/gregorywagner/Software/gotmtool/gotm_build.py", line 8, in <module>
    from gotmtool.model import Model
  File "/Users/gregorywagner/Software/gotmtool/gotmtool/__init__.py", line 1, in <module>
    from .model import *
  File "/Users/gregorywagner/Software/gotmtool/gotmtool/model.py", line 10, in <module>
    from .io import *
  File "/Users/gregorywagner/Software/gotmtool/gotmtool/io.py", line 9, in <module>
    from ruamel.yaml import YAML
ModuleNotFoundError: No module named 'ruamel'
```

I also tried `gotm_env_init.py`:

```python
(base) gregorywagner:gotmtool/ (master) $ python gotm_env_init.py                                                                                                                   [8:06:29]
Traceback (most recent call last):
  File "/Users/gregorywagner/Software/gotmtool/gotm_env_init.py", line 8, in <module>
    from ruamel.yaml import YAML
ModuleNotFoundError: No module named 'ruamel'
```

What am I doing wrong?

Side question: should we run `gotm_build.py` first? (Does this download and compile GOTM?) If so I can update the readme with instructions.

**Comment by glwagner** [comment]
Ok, after googling around I took the following steps (I installed [anaconda](https://www.anaconda.com/) previously and use `conda` as well as its python installation below)

# Create the conda environment

```bash
$ conda env create -f environment.yml
```

This creates an environment from `environment.yml`. The name of the environment is "`gotm`", as can be seen by inspecting the `environment.yml` (this is also printed in the terminal after the environment is created / installed):

```yaml
name: gotm
channels:
  - conda-forge
dependencies:
  - python=3.9
  - gfortran=11
  - netcdf-fortran
  - cmake
  - xarray
  - scipy
  - ruamel.yaml
  - jupyter
  - notebook
  - matplotlib
  - pip
```

Creating the environment downloads and installs packages, and this takes some time.

# Activate the environment

```bash
$ conda activate gotm
```

# Run `gotm_env_init.py` to setup the directory structure and download gotm files (source code, input data, compiled build, executable)

```bash
python gotm_env_init.py
```

Running this script will initiate a series of prompts about yaml file names, directory names, and clone requests to github that must be answered to install and compile gotm.

Note: if you attempt to run `gotm_build.py` before `gotm_env_init.py`, you will receive an error

```
ERROR: GOTM environment file '.gotm_env.yaml' not found
  Please run gotm_env_init.py to set it up
```

# Run `gotm_build.py` to compile gotm

```bash
$ python gotm_build.py
```

**Comment by glwagner** [comment]
@qingli411 let me know if those instructions are correct and if you'd like me to add them to the README!

**Comment by qingli411** [comment]
Hi @glwagner ! Yes, you are right. I should have mentioned the conda environment it requires… Thanks a lot for writing up these instructions and they look very clear! It would be nice to include them in the README. Could you please create a PR for that?

**Comment by qingli411** [comment]
Just updated the README to include these instructions!
